# Generated by Django 4.2.7 on 2023-12-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('artiste', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('duree', models.DurationField()),
                ('fichier_audio', models.FileField(upload_to='musiques/')),
            ],
        ),
    ]
